[metadata]
name = rospec
author = Paulo Canelas
author_email = pasantos@andrew.cmu.edu
url = https://github.com/pcanelas/rospec
description = A domain specification language for detecting misconfigurations for ROS
long_description = file: README.rst
keywords = ros, specification, misconfiguration
license = Apache License, Version 2.0
include_package_data = True
classifiers =
  Natural Language :: English
  Intended Audience :: Developers
  Programming Language :: Python
  Programming Language :: Python :: 3.9

[options]
python_requires = >= 3.9
install_requires =
  attrs == 25.3.0
  pyyaml == 6.0.2
  sourcelocation == 1.1.8
  typing-extensions == 4.13.2
package_dir =
  =src
packages = find:

[options.entry_points]
console_scripts =
  rospec = rospec.cli:main

[options.packages.find]
where = src

[flake8]
max-line-length = 120